# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('grade', models.CharField(choices=[('1', '5 Primaria'), ('2', '6 Primaria'), ('3', '1 Secundaria'), ('4', '2 Secundaria'), ('5', '3 Secundaria')], max_length=50)),
            ],
        ),
    ]
