# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kid',
                'verbose_name_plural': 'Kids',
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='kid',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
