# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('team', '0004_team_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='school',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
            preserve_default=False,
        ),
    ]
