# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_responsable_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='assistance',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kid',
            name='week_talk',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
