# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20160224_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
