# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='grade',
            field=models.CharField(choices=[('5 Primaria', '5 Primaria'), ('6 Primaria', '6 Primaria'), ('1 Secundaria', '1 Secundaria'), ('2 Secundaria', '2 Secundaria'), ('3 Secundaria', '3 Secundaria')], max_length=50),
        ),
    ]
