# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_auto_20160225_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='responsable',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsable',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
