# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_auto_20160227_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsable',
            name='full_name',
        ),
        migrations.AddField(
            model_name='responsable',
            name='slug',
            field=models.SlugField(blank=True, max_length=152, unique=True),
        ),
    ]
