# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20160227_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=102, unique=True),
        ),
    ]
